{{- if (or .Values.stream.tcp.enable .Values.stream.tcp.map) }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "nginx-ingress.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.controller.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "nginx-ingress.fullname" . }}-tcp
data:
{{ toYaml .Values.stream.tcp.map | indent 2 }}
{{- end }}
